### PR TITLE
Add/edit comments on KB entries; closes #1376

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Review by orthagh — CHANGES_REQUESTED** [review]
Some general comments regarding the design as i didn't found any thing to comment regarding the code:
- the styles of theses buttons is bad (imo) 
image
 
I think the cancel submit button should be more lighter (no background, like a simple link) and have some padding before it. 
Instead of "Add", i suggest "Reply". 

- A new topic or thread group should be more distincted from other ones

- same for the tree indication, a more darker line could enhance understanding (em margin is very good !)

- for reply icon, suggestion: http://fa2png.io/r/font-awesome/mail-reply/?color=2c3e50&margin=0&size=16

- i think this icon could be outed (not sure for this word) of the comment block and set in outer right bottom

**Comment by trasher** [comment]
> the cancel submit button should be more lighter 

Doesn't we have any existing examples in the core actually?

> a more darker line

Yep, we were talking about that in the office last week :)

> for reply icon, suggestion

OK

> i think this icon could be outed (not sure for this word) of the comment block and set in outer right bottom

Hum... I d not understand :/ Just a note: I've based this display on tickets; icons emplacements are the same; are we sure we want similar displays with icons placed at different places?

**Comment by orthagh** [comment]
> > the cancel submit button should be more lighter
> Doesn't we have any existing examples in the core actually?

No.
It's more a recommendation issued from material design specs.
Primary action should be higlighted and secondary lighten.
In core, we haver many examples of Submit / Cancel with the same design, which i think is wrong.
The kb enhancement could be test for a new design for the rest of glpi.

> > i think this icon could be outed (not sure for this word) of the comment block and set in outer right bottom
> Hum... I d not understand :/ Just a note: I've based this display on tickets; icons emplacements are the same; are we sure we want similar displays with icons placed at different places?

Edit inline is ok. The reply is an (new in glpi) action who insert a div (and the editor) under the answer and i think the button action should be at the same place (under the answer)

**Comment by orthagh** [comment]
Some issue with the last version:
image

**Review by orthagh — APPROVED** [review]

**Pull request merged**
